#In this file are stored the URLs and the CSS Selector of the web sites that are scraped
news_sites:
  eluniversal:
    url: [http://www.eluniversal.com.mx]
    queries:
      homepage_article_links: '.field-content a::attr(href), h2.titulo a::attr(href), a::attr(href)' #contains title
      article_body: '.field-name-body p::text, .field-name-body p::text'
      date: 'span.ce12-DatosArticulo_ElementoFecha::text'
      volanta: .nothing''
      article_title: '.h1::text, .ceh-Opinion_Titulo h2::text'
      next_button_link: ''
  elpais:
    url: [https://elpais.com]
    queries:
      homepage_article_links: ".headline a::attr(href)"
      article_body: '.article_body p::text'
      date: 'a.a_ti::text'
      volanta: 'h2.a_st::text'
      article_title: 'h1.a_t::text'
      next_button_link: ''    
  animalpolitico:
    url: [https://www.animalpolitico.com]
    queries:
      homepage_article_links: '.ap_note_link::attr(href)'
      article_body: '.ap_single_content p::text'
      date: '.ap_single_first_info_date::text'
      volanta: ''
      article_title: '.ap_single_first_title::text'
      next_button_link: ''  
  pagina12:
    url: ['https://www.pagna12.com.ar/secciones/el-pais',
                     'https://www.pagina12.com.ar/secciones/economia',
                     'https://www.pagina12.com.ar/secciones/sociedad',
                     'https://www.pagina12.com.ar/suplementos/cultura-y-espectaculos',
                     'https://www.pagina12.com.ar/secciones/ciencia',
                     'https://www.pagina12.com.ar/secciones/el-mundo',
                     'https://www.pagina12.com.ar/secciones/deportes',
                     'https://www.pagina12.com.ar/secciones/psicologia']
    queries:
      homepage_article_links: ".headline a"
      article_body: '.article_body p'
      date: ''
      volanta: ''
      article_title: '.a_t'
      next_button_link: ''     